include:
  - path:
      - api/docker-compose.api.prod.yml
      - web/docker-compose.web.prod.yml
      - doc/docker-compose.doc.prod.yml
      - australia/docker-compose.australia.prod.yml
      - docker-compose.prod.override.yml
